# Generated by Django 3.1.6 on 2021-02-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('Complain_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=30)),
                ('Description', models.TextField(blank=True, max_length=150)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
