# Generated by Django 3.1.6 on 2021-02-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210218_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='date',
            new_name='Assigned_Date',
        ),
        migrations.AddField(
            model_name='complaint',
            name='Completed_Date',
            field=models.DateField(blank=True, default='2020-02-19'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
