# Generated by Django 3.1.6 on 2021-02-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210219_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Completed_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Working', 'Working'), ('Done', 'Done')], default='Pending', max_length=10),
        ),
    ]
