# Generated by Django 3.1.6 on 2021-02-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210219_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Completed_Date',
            field=models.DateField(null=True),
        ),
    ]
